sudo: required
language: c
os:
  - linux
services:
  - docker
env:
  - DOCKER_IMAGE=centos:6
  - DOCKER_IMAGE=centos:7
  - DOCKER_IMAGE=debian:stable
  - DOCKER_IMAGE=ubuntu:latest

before_script:
  # these steps prep the source as if it were a distribution tarball
  - sudo apt-get install -y gperf ragel bison
  - sh autogen.sh
  - ./configure
  - make -C drmaa_utils conf_tab.c conf_tab.h datetime_tab.c datetime_tab.h drmaa_attrib.c timedelta.c
  - make distclean
  # set up build env
  - |
    case "$DOCKER_IMAGE" in
        centos:*)
            docker run --cidfile .cid $DOCKER_IMAGE yum groupinstall -y 'development tools'
            ;;
        debian:*|ubuntu:*)
            docker run --cidfile .cid --env DEBIAN_FRONTEND=noninteractive $DOCKER_IMAGE /bin/sh -c 'apt-get -qq update && apt-get install -y build-essential'
            ;;
        *)
            echo "unsupported image: $DOCKER_IMAGE"
            return 1
            ;;
    esac
  - docker commit $(cat .cid) ci/$DOCKER_IMAGE

script:
  - docker run --volume $(pwd):$(pwd) --workdir $(pwd) --user $(id -u):$(id -g) ci/$DOCKER_IMAGE ./configure
  - docker run --volume $(pwd):$(pwd) --workdir $(pwd) --user $(id -u):$(id -g) ci/$DOCKER_IMAGE make
